// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class BodiesDb : DataConnection
	{
		public BodiesDb()
		{
			InitDataContext();
		}

		public BodiesDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public BodiesDb(LinqToDBConnectionOptions<BodiesDb> options)
			: base(options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<AstralBody> AstralBodies => this.GetTable<AstralBody>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static AstralBody? Find(this ITable<AstralBody> table, string body)
		{
			return table.FirstOrDefault(e => e.Body == body);
		}

		public static Task<AstralBody?> FindAsync(this ITable<AstralBody> table, string body, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Body == body, cancellationToken);
		}
		#endregion
	}
}
